name: easy_byke
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/fb-icon.png
    - assets/images/g-icon.png
    - assets/images/tw-icon.png
    - assets/images/LOGO.png
    - assets/images/user.png

fonts:
  - family: VALORANT
    fonts:
      - asset: assets/fonts/ValorantFont.ttf

